sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build python-transformation
script: docker-compose run --rm --entrypoint sh python-transformation /code/run_tests.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
notifications: 
  slack: "keboola:vkkYKFmIcqEe0ZpPKKAMJWfP"
