language: python

python: 
  - "3.5"

install: 
  - "pip install pytest-cov"
  - "pip install git+git://github.com/keboola/python-docker-application.git"

before_install:
  - export KBC_DATA_DIR=$TRAVIS_BUILD_DIR/test/data/

script: 
  - "py.test --cov=transformation --cov-report term-missing"

notifications: 
  slack: "keboola:vkkYKFmIcqEe0ZpPKKAMJWfP"
