sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build python-transformation
script: docker-compose run --rm --entrypoint python python-transformation -m unittest discover
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
notifications:
  slack: keboola:NCe8LwHlAyQBD4KS8BM0JkuA