sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build python-transformation
script: docker-compose run --rm --entrypoint python python-transformation -m unittest discover
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
notifications:
  email: false
  slack:
    secure: L6NPz1S3iHDvmr+69b0yL2V/JwmZE5+ecdoZAdnplT9ciiT7UoxFIe4VlPKi3ILeQxG0eUau+ZN0HifV4eq9DnqO/056IFRsgfb9Bcz0rEdILE1NfiPu1olfbKa5XpmcHX2jCWHn5YPBA53OAds4GGzVT8JyqiA9T+yhOu/+5Z9CICYLk2w7RSQ77pNup+jBy6F3sbXWtp/qA4CHBRU7N7tmSBzdE1jiJR4YW1q1dXgVvvshSogfQErEQBzRcBNoiQLrjFLLchHPsivXI3vHVxKxUa55Jl/pn72q7lb5I7L0vDmPPhvHLmsw1uJR48+ddEKZwoNMy8GYvqOlYr1llxP0nFLJktnI/Hr4U0lP2YKLomdUBlIu+0PZE4CRQaK1QQeqvpEw6TJAPE+f7OZH+I3SlPxqIzFbmz6gwjCytWN+WSm8JU2tAC0Vp9pEmMDA8D5YNcSrdjVCdAqP01h+FvLUCssJvyanpnwCO4DH8Y54IZ2MbXOsL3x3L+v50HiJUjNXj2ByytwUfbI/3FrdF72bxdzb48iLlbYy8Rz/ACEEfI+cwz/0gdnxYKW0uwF2rbpV0hMSRii2wB42/j/GWWOUJeJxHtUZz07Hr2S6ZtDsxFmxmsdSZe0nG2e6FIG3PEpmWYj94nlrNZdC8S1wYV0PIQ0+A4MpCIh5YlzDPnI=
